# fly.toml app configuration file generated for tweetcheck-backend on 2025-01-29T11:56:06-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tweetcheck-backend'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  FLASK_APP = 'run.py'
  FLASK_ENV = 'production'

[[mounts]]
  source = 'tweetcheck_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
